export const GET_TICKETS_LIST = 'GET_TICKETS_LIST_REQUEST';
export const GET_TICKETS_LIST_SUCCESS = 'GET_TICKETS_LIST_SUCCESS';
export const GET_TICKETS_LIST_FAIL = 'GET_TICKETS_LIST_FAIL';

export const TOGGLE_STOP_FILTER = 'TOGGLE_STOP_FILTER';
export const CHECK_ALL_STOPS_FILTER = 'CHECK_ALL_STOPS_FILTER';
export const UNCHECK_ALL_STOPS_FILTER = 'UNCHECK_ALL_STOPS_FILTER';
