export const GET_TICKETS_LIST = 'GET_TICKETS_LIST_REQUEST';
export const GET_TICKETS_LIST_SUCCESS = 'GET_TICKETS_LIST_SUCCESS';
export const GET_TICKETS_LIST_FAIL = 'GET_TICKETS_LIST_FAIL';

export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const CHECK_ALL_FILTERS = 'CHECK_ALL_FILTERS';
export const UNCHECK_ALL_FILTERS = 'UNCHECK_ALL_FILTERS';
