// tickets types
export const GET_TICKETS_LIST = 'GET_TICKETS_LIST_REQUEST';
export const GET_TICKETS_LIST_SUCCESS = 'GET_TICKETS_LIST_SUCCESS';
export const GET_TICKETS_LIST_FAIL = 'GET_TICKETS_LIST_FAIL';
export const UPDATE_TICKETS_LIST = 'UPDATE_TICKETS_LIST';

// filters types
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const CHECK_ALL_FILTERS = 'CHECK_ALL_FILTERS';
export const UNCHECK_ALL_FILTERS = 'UNCHECK_ALL_FILTERS';

// currency types
export const TOGGLE_CURRENCY = 'TOGGLE_CURRENCY';
export const GET_CURRENCY_RATE = 'GET_CURRENCY_RATE';
export const GET_CURRENCY_RATE_SUCCESS = 'GET_CURRENCY_RATE_SUCCESS';
export const GET_CURRENCY_RATE_FAIL = 'GET_CURRENCY_RATE_FAIL';
